Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -41,46 +41,46 @@ prepare:
     paths:
       - ../charts/
 
-deploy:
-  stage: deploy
-  image: samuelrak/helm:master
-  rules:
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      variables:
-        TARGET_NS: $CI_COMMIT_REF_SLUG
-        NEW_HOST: "$CI_COMMIT_REF_SLUG.mydomain.org"
-    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
-      variables:
-        TARGET_NS: prod
-        NEW_HOST: "www.mydomain.org"
-  script:
-    - |
-      ls
-      if [ -d frontend ]; then
-          yq e -i '.ingress.hosts[0].host="'$NEW_HOST'"' frontend/values.yaml
-        else
-          echo "Error: frontend directory not found"
-          exit 1
-        fi
-      CHARTS=("backauth" "backtours" "databases" "frontend")
-      for chart in "${CHARTS[@]}"; do
-          if [ -d $chart ]; then
-              if [ -f $chart/Chart.yaml ]; then
-                  cd ./$chart
-                  helm dependency update
-                  helm upgrade --install $chart . --namespace $TARGET_NS
-                  cd .. 
-              else
-                  echo "Error: $chart directory does not contain Chart.yaml file, skipping upgrade"
-              fi
-          else
-              echo "Error: $chart directory not found, skipping upgrade"
-          fi
-      done
-      echo $CI_COMMIT_REF_SLUG
-  environment:
-    name: $TARGET_NS
-    url: $NEW_HOST
+# deploy:
+#   stage: deploy
+#   image: samuelrak/helm:master
+#   rules:
+#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+#       variables:
+#         TARGET_NS: $CI_COMMIT_REF_SLUG
+#         NEW_HOST: "$CI_COMMIT_REF_SLUG.mydomain.org"
+#     - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
+#       variables:
+#         TARGET_NS: prod
+#         NEW_HOST: "www.mydomain.org"
+#   script:
+#     - |
+#       ls
+#       if [ -d frontend ]; then
+#           yq e -i '.ingress.hosts[0].host="'$NEW_HOST'"' frontend/values.yaml
+#         else
+#           echo "Error: frontend directory not found"
+#           exit 1
+#         fi
+#       CHARTS=("backauth" "backtours" "databases" "frontend")
+#       for chart in "${CHARTS[@]}"; do
+#           if [ -d $chart ]; then
+#               if [ -f $chart/Chart.yaml ]; then
+#                   cd ./$chart
+#                   helm dependency update
+#                   helm upgrade --install $chart . --namespace $TARGET_NS
+#                   cd .. 
+#               else
+#                   echo "Error: $chart directory does not contain Chart.yaml file, skipping upgrade"
+#               fi
+#           else
+#               echo "Error: $chart directory not found, skipping upgrade"
+#           fi
+#       done
+#       echo $CI_COMMIT_REF_SLUG
+#   environment:
+#     name: $TARGET_NS
+#     url: $NEW_HOST
 
 downstream_build:
   image: samuelrak/helm:latest
@@ -89,7 +89,31 @@ downstream_build:
     - |
       if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
         echo "Triggering downstream build..."
-        curl -v --request POST --form "token=${DOWNSTREAM_PROJECT_TRIGGER_TOKEN}" --form ref=main https://gitlab.kosickaakademia.sk/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/trigger/pipeline
+        case "$(dirname $CI_COMMIT_PATH)/" in
+          "frontend/")
+            TOKEN="${DOWNSTREAM_PROJECT_TRIGGER_TOKEN_FE}"
+            PROJECT_ID="${DOWNSTREAM_PROJECT_ID_FE}"
+            ;;
+          "backend-auth/")
+            TOKEN="${DOWNSTREAM_PROJECT_TRIGGER_TOKEN_BE_AUTH}"
+            PROJECT_ID="${DOWNSTREAM_PROJECT_ID_BE_AUTH}"
+            ;;
+          "backend-tours/")
+            TOKEN="${DOWNSTREAM_PROJECT_TRIGGER_TOKEN_BE_TOURS}"
+            PROJECT_ID="${DOWNSTREAM_PROJECT_ID_BE_TOURS}"
+            ;;
+          "databases/")
+            TOKEN="${DOWNSTREAM_PROJECT_TRIGGER_TOKEN_DB}"
+            PROJECT_ID="${DOWNSTREAM_PROJECT_ID_DB}"
+            ;;
+          *)
+            echo "Unknown folder: $(dirname $CI_COMMIT_PATH)"
+            exit 1
+            ;;
+        esac
+
+        curl -v --request POST --form "token=${TOKEN}" --form ref=main "https://gitlab.kosickaakademia.sk/api/v4/projects/${PROJECT_ID}/trigger/pipeline"
+
       else
         echo "Not triggering downstream build as branch is not default."
       fi
