Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -57,7 +57,12 @@ deploy:
     - |
       ls
       helm dependency update
-  
+      if [ -d frontend ]; then
+          yq e -i '.ingress.hosts[0].host="'$NEW_HOST'"' frontend/values.yaml
+        else
+          echo "Error: frontend directory not found"
+          exit 1
+        fi
       CHARTS=("backauth" "backtours" "databases" "frontend")
       for chart in "${CHARTS[@]}"; do
           if [ -d $chart ]; then
